import { validateAndSanitizeInvoiceItemList } from '../utils/helpers';

type LocalFile={name:string;mimeType?:string;base64?:string;pageImages?:string[];extractedText?:string;tableData?:any[]};
const AR='٠١٢٣٤٥٦٧٨٩',FA='۰۱۲۳۴۵۶۷۸۹'; let itemCounter=0;
const normDigits=(v:any)=>String(v??'').replace(/[٠-٩]/g,d=>String(AR.indexOf(d))).replace(/[۰-۹]/g,d=>String(FA.indexOf(d)));
const norm=(v:any)=>normDigits(v).replace(/[\u064B-\u065F\u0670]/g,'').replace(/[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g,'').replace(/\r/g,'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const compact=(v:any)=>norm(v).toLowerCase().replace(/[\s:：._\-\/]+/g,'');
function num(v:any){if(typeof v==='number'&&Number.isFinite(v))return v;let s=normDigits(v).trim().replace(/[٬،]/g,',').replace(/\s/g,'').replace(/[^0-9.,+\-]/g,'');if(!s)return 0;const c=s.lastIndexOf(','),d=s.lastIndexOf('.');if(c>=0&&d>=0)s=c>d?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(c>=0)s=/,\d{1,2}$/.test(s)?s.replace(',','.'):s.replace(/,/g,'');const n=Number(s);return Number.isFinite(n)?n:0;}
function pure(v:any){const s=normDigits(v).trim().replace(/[٬،]/g,',').replace(/\s/g,'');return /^[-+]?(?:\d{1,3}(?:[,.]\d{3})+|\d+)(?:[.]\d+)?$/.test(s);}
function formatted(v:string){const s=normDigits(v).trim();return /\d[,.]\d{1,2}$/.test(s)||/\d{1,3}(?:,\d{3})+(?:\.\d+)?$/.test(s);}
function dateLike(v:any){const s=normDigits(v).trim();if(/^\d+(?:\.\d+)?\s*[\/\*]\s*\d+(?:\.\d+)?\s*(?:mg|g|ml|mcg|iu|مجم|ملجم|مل|جم)?$/i.test(s))return false;return /^(?:20\d{2}[/.\-]\d{1,2}(?:[/.\-]\d{1,2})?|\d{1,2}[/.\-]\d{1,2}[/.\-](?:20)?\d{2}|\d{1,2}[/.\-](?:20)?\d{2})$/.test(s);}
function cells(row:any):string[]{if(Array.isArray(row))return row.map(norm).filter(Boolean);if(row&&typeof row==='object')return Object.values(row).map(norm).filter(Boolean);const s=String(row??'').trim();if(!s)return [];if(s.includes('|'))return s.split(/\s*\|\s*/).map(norm).filter(Boolean);if(s.includes('\t'))return s.split(/\t+/).map(norm).filter(Boolean);return s.split(/\s{2,}/).map(norm).filter(Boolean);}
function header(v:string){return /^(page|صفحة|total|subtotal|grandtotal|المجموع|الإجمالي|اجمالي|date|التاريخ|invoice|فاتورة|supplier|المورد|customer|العميل|currency|العملة|item|الصنف|الصنفالدواء|description|الوصف|price|السعر|quantity|الكمية|qty|عدد|no|رقم|code|كود|barcode|باركود)$/.test(compact(v));}
function nameScore(v:string){if(!v||header(v)||dateLike(v)||pure(v)||!/[A-Za-z\u0600-\u06FF]/.test(v))return -1e6;let s=v.length;if(/mg|ml|mcg|iu|مجم|ملجم|مل|جم|شراب|كبسول|قرص|أقراص|مرهم|كريم|قطرة|امبول|فيال|بخاخ|كيس|علبة|باكيت|شريط|تيوب|توپ/i.test(v))s+=35;return s;}
function cleanName(v:string){let s=norm(v).replace(/^[\s:؛,\-–—|]+|[\s:؛,\-–—|]+$/g,'').trim();s=s.replace(/\s+\d{4,12}$/,'').trim();if(/(?:كيس|علبة|علب|باكيت|شريط|حبة|حبات|قرص|كبسول|امبول|فيال|تيوب|توپ)\s+\d{2,3}$/i.test(s))s=s.replace(/\s+\d{2,3}$/,'').trim();return s;}
function unitOf(cs:string[]){const p=/^(كيس|علبة|علب|باكيت|شريط|كرتون|حبة|حبات|قرص|كبسول|كبسولة|امبول|أمبول|فيال|تيوب|توپ|قطعة|وحدة|شرائط|tab|tabs|cap|caps|vial|amp|box)$/i;return cs.find(x=>p.test(x))||'علبة';}
function priceOf(ns:{value:string;n:number;i:number}[],ni:number){const a=ns.filter(x=>x.i>ni&&x.n>0);if(!a.length)return null;return a.map((x,o)=>{let s=0;if(o===2)s+=14;else if(o===1)s+=9;else if(o===0)s+=2;else s-=o*2;if(formatted(x.value))s+=8;if(x.n>=100)s+=3;if(x.n<=20&&Number.isInteger(x.n))s-=7;if(x.n>=100000)s-=7;return {...x,s};}).sort((a,b)=>b.s-a.s)[0]||null;}
function quantityOf(ns:{n:number;i:number}[],ni:number,pi:number|null){return ns.filter(x=>Number.isInteger(x.n)&&x.n>=1&&x.n<=1000&&x.i!==pi).sort((a,b)=>Math.abs(a.i-ni)-Math.abs(b.i-ni))[0]?.n||1;}
function parseRow(row:any,idx:number){const cs=cells(row);if(!cs.length||cs.every(header))return null;let name='',ni=-1,best=-1e6;cs.forEach((c,i)=>{const s=nameScore(c);if(s>best){best=s;name=c;ni=i;}});if(ni<0)return null;const ns=cs.map((c,i)=>({value:c,n:num(c),i})).filter(x=>pure(x.value)&&!dateLike(x.value)&&x.n>=0&&x.n<1e8);const numeric=ns.filter(x=>!(x.i===0&&Number.isInteger(x.n)&&x.n===idx+1&&x.n<10000));if(!numeric.length)return null;const pc=priceOf(numeric,ni),pi=pc?.i??null,p=pc?.n||0,q=quantityOf(numeric,ni,pi);let total=p*q;if(p>0){const match=numeric.filter(x=>x.i>(pi??ni)&&x.i!==pi&&x.n>0).find(x=>Math.abs(x.n-total)<=Math.max(1,total*.03));if(match)total=match.n;}const n=cleanName(name);if(n.length<2)return null;return {id:`local-${Date.now()}-${itemCounter++}`,itemName:n,quantity:q,unit:unitOf(cs),unitPrice:p,totalPrice:total,bonusScheme:'',discountPercent:0,notes:'',rawText:cs.join(' | ')};}
function parseRows(rs:any[]){const out:any[]=[],seen=new Set<string>();rs.forEach((r,i)=>{const x=parseRow(r,i);if(!x)return;const k=`${compact(x.itemName)}|${x.quantity}|${x.unitPrice}|${x.totalPrice}`;if(!seen.has(k)){seen.add(k);out.push(x);}});return out;}
function first(text:string,ps:RegExp[]){for(const p of ps){const m=text.match(p);if(m?.[1])return norm(m[1]);}return '';}
function meta(text:string,names:string[]){const lines=text.split('\n').map(norm).filter(Boolean).join('\n');const dn=first(lines,[/(?:invoice|inv|فاتورة|الفاتورة|رقم\s*الفاتورة|رقم\s*المستند|document\s*(?:no|number)|order\s*(?:no|number))\s*[:#№-]?\s*([A-Z0-9][A-Z0-9\/_-]{1,30})/i]);const dr=first(lines,[/(?:date|dated|تاريخ|التاريخ)\s*[:：-]?\s*([0-9]{1,4}[/.\-][0-9]{1,2}(?:[/.\-][0-9]{2,4})?)/i]);let title=/مرتجع|sales\s*return|return\s*invoice/i.test(lines)?'مرتجع':/أمر\s*شراء|purchase\s*order/i.test(lines)?'أمر شراء':/قائمة\s*أسعار|price\s*list/i.test(lines)?'قائمة أسعار':/فاتورة|invoice/i.test(lines)?'فاتورة':names.length===1?names[0]:names.join(' + ');return{documentNumber:dn,documentDate:dr,partyName:'',currency:first(lines,[/(?:currency|العملة|عملة)\s*[:：-]?\s*([^\n]+)/i,/(YER|SAR|USD|EUR|AED|ريال\s*يمني|ريال|دولار|يورو|درهم)/i]),title};}
function dataUrl(v:string,m='image/jpeg'){return /^data:/i.test(v)?v:`data:${m};base64,${v}`;}
async function prep(v:string){if(typeof window==='undefined')return v;return new Promise<string>(r=>{const img=new Image();img.onload=()=>{try{const max=2800,sc=Math.min(2,max/Math.max(img.naturalWidth||1,img.naturalHeight||1)),w=Math.max(1,Math.round((img.naturalWidth||img.width)*sc)),h=Math.max(1,Math.round((img.naturalHeight||img.height)*sc));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');if(!x)return r(v);x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(img,0,0,w,h);r(c.toDataURL('image/png'));}catch{r(v);}};img.onerror=()=>r(v);img.src=v;});}
export async function analyzeDocumentLocally(params:{files:LocalFile[];targetType:'order'|'invoice'|'price_list';knownMedicines?:string[];knownSuppliers?:string[];onProgress?:(p:number,m:string,s?:number)=>void}){const{files,targetType,onProgress}=params;if(!files.length)throw new Error('لا توجد ملفات للتحليل المحلي');let text='',raw:any[]=[],pages=0,done=0;for(const f of files){pages+=f.pageImages?.length||(f.base64&&/image\//i.test(f.mimeType||'')?1:0);if(f.tableData?.length)raw.push(...f.tableData);if(f.extractedText)text+=`\n${f.extractedText}`;}pages=Math.max(1,pages);for(const f of files){const ps=f.pageImages?.length?f.pageImages:(f.base64&&/image\//i.test(f.mimeType||'')?[f.base64]:[]);if(!ps.length)continue;const{ocrImageDataUrlWithLayout}=await import('./localOcr');for(let i=0;i<ps.length;i++){onProgress?.(20+Math.round((done/pages)*10),`تشغيل OCR المحلي للصفحة ${i+1} من ${ps.length}...`,2);const o=await ocrImageDataUrlWithLayout(await prep(dataUrl(ps[i],f.mimeType||'image/jpeg')),p=>onProgress?.(20+Math.round(((done+p/100)/pages)*68),`استخراج البيانات محلياً...`,2));if(o.text)text+=`\n${o.text}`;if(o.layoutText)raw.push(...o.layoutText.split('\n'));else if(o.text)raw.push(...o.text.split('\n'));done++;}}const items=validateAndSanitizeInvoiceItemList(parseRows(raw));const md=meta(text,files.map(f=>f.name));const total=items.reduce((s:any,x:any)=>s+(Number(x.totalPrice)||0),0);onProgress?.(94,`اكتمل التحليل المحلي: ${items.length} صنفاً`,3);return{detectedType:targetType,documentTitle:md.title,partyName:md.partyName,documentNumber:md.documentNumber,documentDate:md.documentDate,currency:md.currency,totalAmount:total,items,confidence:items.length?90:40,summary:`تحليل محلي مع ترتيب أعمدة RTL واستخراج الأسعار، دون إرسال الملف إلى Gemini.`,rawText:text.trim()};}
