import { createWorker, PSM } from 'tesseract.js';

type Word={text:string;confidence:number;bbox:{x0:number;y0:number;x1:number;y1:number}};
let workerPromise:ReturnType<typeof createWorker>|null=null;
const wait=<T,>(p:Promise<T>,ms:number,label:string)=>new Promise<T>((resolve,reject)=>{const t=window.setTimeout(()=>reject(new Error(`${label} timed out after ${ms}ms`)),ms);p.then(v=>{window.clearTimeout(t);resolve(v)},e=>{window.clearTimeout(t);reject(e)})});
function getWorker(){if(!workerPromise)workerPromise=wait(createWorker('ara+eng',1,{logger:()=>undefined,workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@7.0.0',langPath:'https://cdn.jsdelivr.net/gh/naptha/tessdata@gh-pages/4.0.0',cachePath:'purchasemate-ocr',cacheMethod:'write',gzip:true,workerBlobURL:true}).then(async w=>{await w.setParameters({tessedit_pageseg_mode:PSM.SINGLE_COLUMN,preserve_interword_spaces:'1',user_defined_dpi:'300'});return w}),150000,'تشغيل محرك OCR المحلي').catch(e=>{workerPromise=null;throw e}));return workerPromise}
function clean(s:string){return String(s||'').replace(/[\u0000-\u001F]/g,'').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g,'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/\s+/g,' ').trim()}
function isArabic(s:string){const a=(s.match(/[\u0600-\u06FF]/g)||[]).length,l=(s.match(/[A-Za-z]/g)||[]).length;return a>0&&a>=l}
function cell(words:Word[]){const s=words.map(w=>w.text).join(' ');return [...words].sort((a,b)=>isArabic(s)?b.bbox.x0-a.bbox.x0:a.bbox.x0-b.bbox.x0).map(w=>clean(w.text)).filter(Boolean).join(' ')}
function buildLayout(words:Word[]){const ws=words.filter(w=>w.text.trim()&&Number.isFinite(w.confidence)&&w.confidence>=18);if(!ws.length)return'';const hs=ws.map(w=>Math.max(1,w.bbox.y1-w.bbox.y0)).sort((a,b)=>a-b),med=hs[Math.floor(hs.length/2)]||20,tol=Math.max(7,med*.7),rows:Word[][]=[];for(const w of ws){const cy=(w.bbox.y0+w.bbox.y1)/2;let r=rows.find(q=>Math.abs(cy-q.reduce((s,x)=>s+(x.bbox.y0+x.bbox.y1)/2,0)/q.length)<=tol);if(!r){r=[];rows.push(r)}r.push(w)}rows.sort((a,b)=>Math.min(...a.map(w=>w.bbox.y0))-Math.min(...b.map(w=>w.bbox.y0));return rows.map(row=>{const lr=[...row].sort((a,b)=>a.bbox.x0-b.bbox.x0);const gaps=lr.slice(1).map((w,i)=>Math.max(0,w.bbox.x0-lr[i].bbox.x1)).filter(g=>g>2).sort((a,b)=>a-b),mg=gaps[Math.floor(gaps.length/2)]||8,cut=Math.max(14,mg*2.4),cs:Word[][]=[];for(const w of lr){const last=cs[cs.length-1];if(!last||w.bbox.x0-last[last.length-1].bbox.x1>=cut)cs.push([w]);else last.push(w)}return cs.reverse().map(cell).filter(Boolean).join(' | ')}).filter(Boolean).join('\n')}
async function prepare(src:string){if(typeof window==='undefined')return[{image:src,mode:PSM.SINGLE_COLUMN}];return new Promise<{image:string;mode:PSM}[]>(resolve=>{const im=new Image();im.onload=()=>{try{const max=2800,w0=im.naturalWidth||im.width||1,h0=im.naturalHeight||im.height||1,s=Math.min(2,max/Math.max(w0,h0)),w=Math.max(1,Math.round(w0*s)),h=Math.max(1,Math.round(h0*s)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});if(!x)return resolve([{image:src,mode:PSM.SINGLE_COLUMN}]);x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(im,0,0,w,h);const base=c.toDataURL('image/png'),px=x.getImageData(0,0,w,h),g=new Uint8ClampedArray(w*h);let mn=255,mx=0;for(let i=0,j=0;i<px.data.length;i+=4,j++){const v=Math.round(.299*px.data[i]+.587*px.data[i+1]+.114*px.data[i+2]);g[j]=v;mn=Math.min(mn,v);mx=Math.max(mx,v)}const make=(thr=false)=>{const o=x.createImageData(w,h),r=Math.max(1,mx-mn);for(let i=0,j=0;i<g.length;i++,j+=4){const v=thr?(g[i]>168?255:0):Math.round((g[i]-mn)/r*255);o.data[j]=o.data[j+1]=o.data[j+2]=Math.max(0,Math.min(255,v));o.data[j+3]=255}x.putImageData(o,0,0);return c.toDataURL('image/png')};resolve([{image:base,mode:PSM.SINGLE_COLUMN},{image:make(),mode:PSM.SINGLE_BLOCK},{image:make(true),mode:PSM.SPARSE_TEXT}])}catch{resolve([{image:src,mode:PSM.SINGLE_COLUMN}])}};im.onerror=()=>resolve([{image:src,mode:PSM.SINGLE_COLUMN}]);im.src=src})}
function merge(ts:string[]){const seen=new Set<string>(),out:string[]=[];for(const t of ts)for(const l of t.split('\n').map(clean).filter(Boolean)){const k=l.toLowerCase().replace(/\s+/g,' ');if(!seen.has(k)){seen.add(k);out.push(l)}}return out.join('\n')}
export async function ocrImageDataUrlWithLayout(src:string,cb?:(p:number)=>void){if(!src||typeof window==='undefined')return{text:'',layoutText:''};try{const w=await getWorker(),vs=await prepare(src),texts:string[]=[],layouts:string[]=[];for(let i=0;i<vs.length;i++){const v=vs[i];await w.setParameters({tessedit_pageseg_mode:v.mode,preserve_interword_spaces:'1',user_defined_dpi:'300'});cb?.(10+i*25);const r=await wait(w.recognize(v.image),i===0?180000:120000,`تحليل الصورة محلياً (${i+1})`),t=String(r?.data?.text||'').trim(),words=((r?.data as any)?.words||[]) as Word;if(t)texts.push(t);const l=buildLayout(words);if(l)layouts.push(l);if(i===0&&t.length>180&&words.length>25)break}cb?.(100);return{text:merge(texts),layoutText:merge(layouts)}}catch(e){workerPromise=null;throw e}}
export async function ocrImageDataUrl(src:string,cb?:(p:number)=>void){const r=await ocrImageDataUrlWithLayout(src,cb);return[r.text,r.layoutText].filter(Boolean).join('\n')}
export async function ocrPdfPages(pages:string[],cb?:(p:number,t:number)=>void){const out:string[]=[];for(let i=0;i<(pages||[]).length;i++){const t=await ocrImageDataUrl(pages[i],p=>cb?.(i+p/100,pages.length));if(t)out.push(`--- OCR الصفحة ${i+1} ---\n${t}`)}return out.join('\n\n').trim()}
