import { createWorker, PSM } from 'tesseract.js';

type Word = { text: string; confidence: number; bbox: { x0:number;y0:number;x1:number;y1:number } };
let workerPromise: ReturnType<typeof createWorker> | null = null;
const wait=<T,>(p:Promise<T>,ms:number,label:string)=>new Promise<T>((resolve,reject)=>{const t=window.setTimeout(()=>reject(new Error(`${label} timed out after ${ms}ms`)),ms);p.then(v=>{window.clearTimeout(t);resolve(v)},e=>{window.clearTimeout(t);reject(e)})});
function getWorker(){if(!workerPromise){workerPromise=wait(createWorker('ara+eng',1,{logger:()=>undefined,workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@7.0.0',langPath:'https://cdn.jsdelivr.net/gh/naptha/tessdata@gh-pages/4.0.0',cachePath:'purchasemate-ocr',cacheMethod:'write',gzip:true,workerBlobURL:true}).then(async w=>{await w.setParameters({tessedit_pageseg_mode:PSM.SINGLE_COLUMN,preserve_interword_spaces:'1',user_defined_dpi:'300'});return w}),150000,'تشغيل محرك OCR المحلي').catch(e=>{workerPromise=null;throw e})}return workerPromise}
function clean(v:string){return String(v||'').replace(/[\u0000-\u001F]/g,' ').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[\u200E\u200F\u202A-\u202E\u2066-\u2069]/g,'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/\s+/g,' ').trim()}
function arabic(v:string){const a=(v.match(/[\u0600-\u06FF]/g)||[]).length,l=(v.match(/[A-Za-z]/g)||[]).length;return a>0&&a>=l}
function buildCell(words:Word[]){const text=words.map(w=>w.text).join(' ');const ordered=[...words].sort((a,b)=>arabic(text)?b.bbox.x0-a.bbox.x0:a.bbox.x0-b.bbox.x0);return ordered.map(w=>clean(w.text)).filter(Boolean).join(' ')}
function buildLayout(words:Word[]){const usable=words.filter(w=>w.text.trim()&&Number.isFinite(w.confidence)&&w.confidence>=45);if(!usable.length)return '';const heights=usable.map(w=>Math.max(1,w.bbox.y1-w.bbox.y0)).sort((a,b)=>a-b),tol=Math.max(8,(heights[Math.floor(heights.length/2)]||20)*.75);const rows:Word[][]=[];for(const w of usable){const y=(w.bbox.y0+w.bbox.y1)/2;let row=rows.find(r=>{const avg=r.reduce((s,x)=>s+(x.bbox.y0+x.bbox.y1)/2,0)/r.length;return Math.abs(y-avg)<=tol});if(!row){row=[];rows.push(row)}row.push(w)}rows.sort((a,b)=>Math.min(...a.map(w=>w.bbox.y0))-Math.min(...b.map(w=>w.bbox.y0)));return rows.map(row=>{const ltr=[...row].sort((a,b)=>a.bbox.x0-b.bbox.x0);const gaps=ltr.slice(1).map((w,i)=>Math.max(0,w.bbox.x0-ltr[i].bbox.x1)).filter(g=>g>4).sort((a,b)=>a-b);const cut=Math.max(16,(gaps[Math.floor(gaps.length*.5)]||10)*2.2);const cells:Word[][]=[];for(const w of ltr){const last=cells[cells.length-1];if(!last||w.bbox.x0-last[last.length-1].bbox.x1>=cut)cells.push([w]);else last.push(w)}const rtl=cells.some(c=>arabic(c.map(w=>w.text).join(' ')));return (rtl?[...cells].reverse():cells).map(buildCell).filter(Boolean).join(' | ')}).filter(Boolean).join('\n')}
async function prepare(src:string){if(typeof window==='undefined')return[{image:src,mode:PSM.SINGLE_COLUMN}];return new Promise<{image:string;mode:PSM}[]>(resolve=>{const image=new Image();image.onload=()=>{try{const max=3000,sw=image.naturalWidth||image.width||1,sh=image.naturalHeight||image.height||1,scale=Math.min(2.2,max/Math.max(sw,sh)),width=Math.max(1,Math.round(sw*scale)),height=Math.max(1,Math.round(sh*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return resolve([{image:src,mode:PSM.SINGLE_COLUMN}]);ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.imageSmoothingEnabled=true;ctx.drawImage(image,0,0,width,height);const original=canvas.toDataURL('image/png');const px=ctx.getImageData(0,0,width,height),gray=new Uint8ClampedArray(width*height);let min=255,maxV=0;for(let p=0,i=0;i<px.data.length;i+=4,p++){const v=Math.round(.299*px.data[i]+.587*px.data[i+1]+.114*px.data[i+2]);gray[p]=v;min=Math.min(min,v);maxV=Math.max(maxV,v)}const make=(threshold:boolean)=>{const out=ctx.createImageData(width,height),range=Math.max(1,maxV-min);for(let p=0,i=0;p<gray.length;p++,i+=4){const v=threshold?(gray[p]>170?255:0):Math.round((gray[p]-min)/range*255);out.data[i]=out.data[i+1]=out.data[i+2]=v;out.data[i+3]=255}ctx.putImageData(out,0,0);return canvas.toDataURL('image/png')};resolve([{image:original,mode:PSM.SINGLE_COLUMN},{image:make(false),mode:PSM.SINGLE_BLOCK},{image:make(true),mode:PSM.SPARSE_TEXT}])}catch{resolve([{image:src,mode:PSM.SINGLE_COLUMN}])}};image.onerror=()=>resolve([{image:src,mode:PSM.SINGLE_COLUMN}]);image.src=src})}
function merge(texts:string[]){const seen=new Set<string>(),out:string[]=[];for(const text of texts)for(const line of text.split('\n').map(clean).filter(Boolean)){const key=line.toLowerCase().replace(/\s+/g,' ');if(!seen.has(key)){seen.add(key);out.push(line)}}return out.join('\n')}
export async function ocrImageDataUrlWithLayout(src:string,cb?:(progress:number)=>void){if(!src||typeof window==='undefined')return{text:'',layoutText:''};try{const worker=await getWorker(),variants=await prepare(src),texts:string[]=[],layouts:string[]=[];for(let i=0;i<variants.length;i++){const v=variants[i];await worker.setParameters({tessedit_pageseg_mode:v.mode,preserve_interword_spaces:'1',user_defined_dpi:'300'});cb?.(10+i*25);const r=await wait(worker.recognize(v.image),i===0?180000:120000,`تحليل الصورة محلياً (${i+1})`);const text=String(r?.data?.text||'').trim();if(text)texts.push(text);const layout=buildLayout(((r?.data as any)?.words||[]) as Word[]);if(layout)layouts.push(layout);if(i===0&&text.length>500)break}cb?.(100);return{text:merge(texts),layoutText:merge(layouts)}}catch(e){workerPromise=null;throw e}}
export async function ocrImageDataUrl(src:string,cb?:(progress:number)=>void){const r=await ocrImageDataUrlWithLayout(src,cb);return[r.text,r.layoutText].filter(Boolean).join('\n')}
export async function ocrPdfPages(pages:string[],cb?:(page:number,total:number)=>void){const out:string[]=[];for(let i=0;i<(pages||[]).length;i++){const t=await ocrImageDataUrl(pages[i],p=>cb?.(i+p/100,pages.length));if(t)out.push(`--- OCR الصفحة ${i+1} ---\n${t}`)}return out.join('\n\n').trim()}
