import React, { useState, useRef, useEffect } from 'react';
import { FileSpreadsheet, FileText, Camera, Upload, Sparkles, CheckCircle2, AlertCircle, ChevronLeft, ArrowRight, RefreshCw, FileUp, Eye, X, Table, Layers, Building2, ShoppingCart, Receipt, FileCheck, Plus, Trash2, Image as ImageIcon, AlertTriangle, HelpCircle, Clock, ArrowUpRight, Wand2, Check, Loader2, Search, Copy, SlidersHorizontal, ShieldCheck, PenTool, FileCode, Zap, Activity, Terminal } from 'lucide-react';
import { Medicine, Supplier, PharmacyOrder, PurchaseInvoice, MarketPriceRecord } from '../types';
import { parseUploadedFile } from '../utils/documentParser';
import { findSimilarMedicine, SimilarityConflict } from '../utils/similarity';
import { SimilarityResolutionModal } from './SimilarityResolutionModal';
import { DocumentSplitPreview, ExtractedDocumentData } from './DocumentSplitPreview';
import { useBackgroundAnalysis } from '../context/BackgroundAnalysisContext';

interface DocumentUploadViewProps { knownMedicines:Medicine[]; knownSuppliers:Supplier[]; onOrderCreated?:(order:PharmacyOrder)=>void; onInvoiceCreated?:(invoice:PurchaseInvoice)=>void; onMarketPricesImported?:(records:MarketPriceRecord[])=>void; onAddMedicine?:(medicine:Medicine)=>void; onAddSupplier?:(supplier:Supplier)=>void; onNavigate:(tab:string,id?:string)=>void; onBack?:()=>void; }
interface UploadedFileItem { id:string; name:string; type:string; size?:number; mimeType:string; base64?:string; pageImages?:string[]; extractedText?:string; tableData?:Array<Record<string,any>>|Array<any[]>; }

export const DocumentUploadView:React.FC<DocumentUploadViewProps>=({knownMedicines,knownSuppliers,onOrderCreated,onInvoiceCreated,onMarketPricesImported,onAddMedicine,onAddSupplier,onNavigate})=>{
 const [step,setStep]=useState<'select_type'|'intake'|'preview'>('select_type'); const [docType,setDocType]=useState<'order'|'invoice'|'price_list'>('order');
 const [pharmacy,setPharmacy]=useState('صيدلية النخبة المركزية'); const [supplier,setSupplier]=useState(''); const [tab,setTab]=useState<'paste'|'files'|'camera'>('paste'); const [text,setText]=useState('');
 const [files,setFiles]=useState<UploadedFileItem[]>([]); const [mode,setMode]=useState<'standard'|'handwritten'|'table'|'pure_text'>('standard'); const [processing,setProcessing]=useState(false); const [error,setError]=useState<string|null>(null); const [data,setData]=useState<ExtractedDocumentData|null>(null);
 const [conflicts,setConflicts]=useState<SimilarityConflict[]>([]); const [showConflicts,setShowConflicts]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const cameraRef=useRef<HTMLInputElement>(null); const consumed=useRef<string|null>(null);
 const {startDocumentTask,activeTask,clearActiveTask,clearTask}=useBackgroundAnalysis();
 useEffect(()=>{if(activeTask?.type==='document'&&activeTask.status==='completed'&&consumed.current!==activeTask.id&&activeTask.payload?.extractedData){setData(activeTask.payload.extractedData);if(activeTask.payload.uploadedFiles)setFiles(activeTask.payload.uploadedFiles);if(activeTask.payload.targetType)setDocType(activeTask.payload.targetType as any);if(activeTask.payload.partyName)(activeTask.payload.targetType==='order'?setPharmacy:setSupplier)(activeTask.payload.partyName);setProcessing(false);setStep('preview')}else if(activeTask?.type==='document'&&activeTask.status==='processing')setProcessing(true)},[activeTask]);
 const addFiles=async(list:FileList|null)=>{if(!list?.length)return;setError(null);const out:UploadedFileItem[]=[];for(let i=0;i<list.length;i++){try{const p=await parseUploadedFile(list[i]);out.push({id:`file-${Date.now()}-${i}`,name:list[i].name,type:p.fileType,size:list[i].size,mimeType:p.mimeType,base64:p.base64,pageImages:p.pageImages,extractedText:p.extractedText,tableData:p.tableData})}catch(e:any){setError(`${list[i].name}: ${e?.message||'تعذر قراءة الملف'}`)}}setFiles(v=>[...v,...out]);};
 const start=async()=>{setError(null);const all=[...files];if(text.trim())all.unshift({id:`text-${Date.now()}`,name:'نص ملصوق',type:'text',mimeType:'text/plain',extractedText:text.trim()});if(!all.length){setError('يرجى لصق قائمة أو رفع ملف/صورة.');return}setProcessing(true);try{await startDocumentTask({files:all,targetType:docType,partyName:(docType==='order'?pharmacy:supplier).trim()||undefined,extractionMode:mode,knownMedicines,knownSuppliers})}catch(e:any){setError(e?.message||'حدث خطأ أثناء التحليل');setProcessing(false)}};
 const update=(i:number,f:string,v:any)=>{if(!data)return;const items=[...(data.items||[])];items[i]={...items[i],[f]:v};setData({...data,items})}; const remove=(i:number)=>{if(!data)return;setData({...data,items:(data.items||[]).filter((_,x)=>x!==i)})};
 const saveOrder=(party:string,items:any[])=>{const valid=items.filter(i=>String(i.itemName||i.matchedMedicineName||i.rawText||'').trim());if(!valid.length){setError('لا توجد أصناف صالحة للحفظ.');return}const c:SimilarityConflict[]=[];valid.forEach((i,idx)=>{const m=findSimilarMedicine(i.itemName,knownMedicines);if(m?.isNearMatch&&m.existingMedicine.name!==i.itemName)c.push({id:`order-conflict-${idx}`,candidateName:i.itemName,existingMedicine:m.existingMedicine as Medicine,similarityScore:m.similarityScore,unitPrice:Number(i.unitPrice)||0,quantity:Number(i.quantity)||1,supplierName:party,bonusScheme:i.bonusScheme,originalIndex:idx})});if(c.length){setConflicts(c);setShowConflicts(true);return}persistOrder(party,valid)};
 const persistOrder=(party:string,items:any[])=>{const safe=items.map((i:any,idx:number)=>({id:`item-${Date.now()}-${idx}`,rawText:String(i.itemName||i.matchedMedicineName||i.rawText||''),matchedMedicineName:String(i.itemName||i.matchedMedicineName||i.rawText||''),matchedMedicineId:i.matchedMedicineId,quantity:Number(i.quantity)>0?Number(i.quantity):1,unit:String(i.unit||'علبة'),isUncertain:!!i.isUncertain,uncertaintyReason:i.uncertaintyReason,notes:i.notes||''}));const order:PharmacyOrder={id:`order-${Date.now()}`,orderNumber:data?.documentNumber||`ORD-${Date.now().toString().slice(-4)}`,pharmacyName:String(party||pharmacy).trim(),orderDate:data?.documentDate||new Date().toISOString().slice(0,10),status:'reviewed',rawInputText:text||`مستخرج من ${files.length} ملفات/صور`,items:safe,createdTimestamp:Date.now()};onOrderCreated?.(order);if(activeTask?.id)consumed.current=activeTask.id;clearActiveTask();clearTask();setData(null);setFiles([]);setText('');setStep('select_type');onNavigate('price-comparison',order.id)};
 const saveInvoice=(sup:string,items:any[],num?:string,date?:string)=>{const valid=(items||[]).filter(i=>i&&(i.itemName||i.medicineName));if(!valid.length){setError('يرجى إضافة صنف واحد على الأقل.');return}const name=String(sup||supplier||'مورد الفاتورة').trim();const found=knownSuppliers.find(s=>(s.name||'').trim().toLowerCase()===name.toLowerCase());const sid=found?.id||`sup-${name.replace(/\s+/g,'-').toLowerCase()}`;if(!found)onAddSupplier?.({id:sid,name,rating:4.5,notes:'تمت إضافته من الفاتورة',createdDate:date||new Date().toISOString().slice(0,10)});const invItems=valid.map((i:any,idx:number)=>{const q=Number(i.quantity)>0?Number(i.quantity):1;const p=Number(i.unitPrice)>=0?Number(i.unitPrice):0;const sourceTotal=Number(i.totalPrice);return{id:`inv-item-${Date.now()}-${idx}`,itemName:String(i.itemName||i.medicineName),matchedMedicineId:i.matchedMedicineId,quantity:q,unitPrice:p,bonusScheme:String(i.bonusScheme||''),discountPercent:Number(i.discountPercent)||0,totalPrice:Number.isFinite(sourceTotal)&&sourceTotal>0?sourceTotal:p*q,isUncertain:!!i.isUncertain,uncertaintyReason:i.uncertaintyReason}});const total=invItems.reduce((s,i)=>s+i.totalPrice,0);const inv:PurchaseInvoice={id:`inv-${Date.now()}`,invoiceNumber:num||data?.documentNumber||`INV-${Date.now().toString().slice(-4)}`,supplierId:sid,supplierName:name,invoiceDate:date||data?.documentDate||new Date().toISOString().slice(0,10),totalAmount:total,items:invItems,createdTimestamp:Date.now()};onInvoiceCreated?.(inv);if(activeTask?.id)consumed.current=activeTask.id;clearActiveTask();clearTask();setData(null);setFiles([]);setText('');setStep('select_type');onNavigate('reconciliation')};
 const savePrices=(sup:string,items:any[],date?:string)=>{const valid=(items||[]).filter(i=>i&&(i.itemName||i.medicineName));if(!valid.length){setError('يرجى التأكد من وجود أصناف صالحة.');return}const name=String(sup||supplier||'مورد السوق').trim(),sid=`sup-${name.replace(/\s+/g,'-').toLowerCase()}`,d=date||data?.documentDate||new Date().toISOString().slice(0,10);const records:MarketPriceRecord[]=valid.map((i:any,idx)=>{const n=String(i.itemName||i.medicineName).trim();const m=knownMedicines.find(x=>(x.name||'').trim().toLowerCase()===n.toLowerCase());const mid=m?.id||`med-${n.replace(/\s+/g,'-').toLowerCase()}`;if(!m)onAddMedicine?.({id:mid,name:n,category:'أدوية عامة',createdDate:d});return{id:`mp-doc-${Date.now()}-${idx}`,medicineId:mid,medicineName:n,supplierId:sid,supplierName:name,unitPrice:Number(i.unitPrice)||0,invoiceDate:d,bonusScheme:i.bonusScheme||'',discountPercent:Number(i.discountPercent)||undefined,notes:i.notes||'استخراج من عروض الأسعار',createdTimestamp:Date.now()}});onMarketPricesImported?.(records);if(activeTask?.id)consumed.current=activeTask.id;clearActiveTask();clearTask();setData(null);setFiles([]);setText('');setStep('select_type');onNavigate('market-prices')};
 if(step==='preview'&&data)return <div className="space-y-4 max-w-6xl mx-auto" dir="rtl"><DocumentSplitPreview documentType={docType} pharmacyName={pharmacy} supplierName={supplier} uploadedFiles={files} pastedText={text} extractedData={data} knownMedicines={knownMedicines} knownSuppliers={knownSuppliers} onUpdateItem={update} onDeleteItem={remove} onAddItem={()=>setData({...data,items:[{id:`item-${Date.now()}`,itemName:'',quantity:1,unit:'علبة',unitPrice:0,totalPrice:0,bonusScheme:'',expiryDate:'',notes:'',isUncertain:true},...(data.items||[])]})} onConfirmOrder={saveOrder} onConfirmInvoice={saveInvoice} onConfirmPriceList={savePrices} onBackToUpload={()=>setStep('intake')} onResetAll={()=>{setData(null);setFiles([]);setText('');setStep('select_type')}} />{showConflicts&&<SimilarityResolutionModal isOpen conflicts={conflicts} knownMedicines={knownMedicines} onResolve={(res)=>{const items=(data.items||[]).map((it,idx)=>{const r=res.get(`order-conflict-${idx}`);return r?{...it,itemName:r.chosenName,matchedMedicineId:r.medicineId||it.matchedMedicineId}:it});setData({...data,items});setShowConflicts(false);persistOrder(data.partyName||pharmacy,items)}} onCancel={()=>setShowConflicts(false)}/>}</div>;
 if(step==='intake')return <div className="space-y-5 max-w-4xl mx-auto" dir="rtl"><div className="flex items-center justify-between bg-slate-900 p-4 rounded-3xl border border-slate-800"><button onClick={()=>setStep('select_type')} className="px-3 py-2 rounded-xl bg-slate-800 text-slate-300"><ArrowRight className="w-4 h-4 inline"/> رجوع</button><div><span className="text-xs text-teal-300">{docType==='order'?'طلب صيدلية':docType==='invoice'?'فاتورة شراء':'عروض أسعار'}</span><h1 className="text-lg font-black text-white">رفع وتجهيز المستند</h1></div>{docType!=='order'&&<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="اسم المورد (اختياري)" className="bg-slate-950 border border-slate-700 rounded-xl p-2 text-white text-xs"/>}</div><div className="bg-slate-900 border border-slate-800 rounded-3xl p-5 space-y-4"><div className="grid grid-cols-3 gap-2"><button onClick={()=>setTab('paste')} className="p-3 rounded-xl bg-slate-800 text-white">نص</button><button onClick={()=>{setTab('files');fileRef.current?.click()}} className="p-3 rounded-xl bg-slate-800 text-white">ملفات</button><button onClick={()=>{setTab('camera');cameraRef.current?.click()}} className="p-3 rounded-xl bg-slate-800 text-white">كاميرا</button></div><input ref={fileRef} type="file" multiple accept="image/*,.pdf,.xlsx,.xls,.docx,.doc,.csv,.tsv,.ods" onChange={e=>addFiles(e.target.files)} className="hidden"/><input ref={cameraRef} type="file" accept="image/*" capture="environment" onChange={e=>addFiles(e.target.files)} className="hidden"/>{tab==='paste'&&<textarea value={text} onChange={e=>setText(e.target.value)} rows={10} placeholder="الصق قائمة الأصناف والكميات هنا" className="w-full bg-slate-950 border border-slate-800 rounded-2xl p-4 text-white"/>}<div className="text-xs text-slate-400">{files.length} ملف محدد</div>{files.length>0&&<div className="grid grid-cols-2 md:grid-cols-4 gap-2">{files.map(f=><div key={f.id} className="bg-slate-950 p-2 rounded-xl text-xs text-slate-300 truncate">{f.name}<button onClick={()=>setFiles(v=>v.filter(x=>x.id!==f.id))} className="float-left text-red-400"><Trash2 className="w-3 h-3"/></button></div>)}</div>}{error&&<div className="p-3 rounded-xl bg-red-500/10 border border-red-500/30 text-red-300 text-xs">{error}</div>}<div className="flex gap-2"><button onClick={()=>setMode('standard')} className="px-3 py-2 rounded-lg bg-slate-800 text-xs text-white">قياسي</button><button onClick={()=>setMode('handwritten')} className="px-3 py-2 rounded-lg bg-slate-800 text-xs text-white">خط يد</button><button onClick={start} disabled={processing} className="flex-1 py-3 rounded-xl bg-teal-500 text-slate-950 font-black">{processing?'جاري التحليل...':'تحليل المستند'}</button></div></div></div>;
 return <div className="space-y-6 max-w-4xl mx-auto" dir="rtl"><div className="text-center py-6"><h1 className="text-3xl font-black text-white">رفع ومعالجة الوثائق الصيدلانية</h1><p className="text-slate-400 text-sm mt-2">اختر نوع العملية ثم ارفع المستند أو الصق النص.</p></div><div className="grid md:grid-cols-3 gap-5"><button onClick={()=>{setDocType('order');setStep('intake')}} className="bg-slate-900 border border-teal-500/30 rounded-3xl p-6 text-right text-white"><ShoppingCart className="w-8 h-8 text-teal-400 mb-3"/><h2 className="text-lg font-black">طلب جديد</h2><p className="text-xs text-slate-400 mt-2">استخراج الأصناف والكميات من الطلب.</p></button><button onClick={()=>{setDocType('invoice');setTab('files');setStep('intake')}} className="bg-slate-900 border border-emerald-500/30 rounded-3xl p-6 text-right text-white"><Receipt className="w-8 h-8 text-emerald-400 mb-3"/><h2 className="text-lg font-black">فاتورة شراء</h2><p className="text-xs text-slate-400 mt-2">استخراج الأصناف والكميات والأسعار والتواريخ.</p></button><button onClick={()=>{setDocType('price_list');setTab('files');setStep('intake')}} className="bg-slate-900 border border-amber-500/30 rounded-3xl p-6 text-right text-white"><Layers className="w-8 h-8 text-amber-400 mb-3"/><h2 className="text-lg font-black">عروض سعر</h2><p className="text-xs text-slate-400 mt-2">استخراج أسعار الموردين والبونص والخصم.</p></button></div></div>;
};
